### ISSUE TITLE
Label bot label identifying problem

### ISSUE THREAD

**Issue by lanking520** [MXNetEdge/mxnet-infrastructure#17]
I am suffered from the current label bot as it cannot add labels if the format is not right.  Such as [CI, Test] only CI is applied and “ Test” not applied. Others like some words without capital letters cannot be applied.

**Comment by harshp8l** [comment]
Users have also experienced a bug when trying to label with specifically 'good first issue'

**Comment by marcoabreu** [comment]
What do you think about some unit tests to ensure all formats work without issues?
