### ISSUE TITLE
[LabelBot] Add Lambda function as SQS consumer

### ISSUE THREAD

**Issue by marcoabreu** [MXNetEdge/mxnet-infrastructure#28]
At the moment, the Lambda function does not register as SQS consumer:

![image](https://user-images.githubusercontent.com/18629099/48162432-5bc3ab80-e2dd-11e8-9b03-178844010031.png)

**Comment by harshp8l** [comment]
Should be resolved with the updating of the serverless version

**Comment by marcoabreu** [comment]
That was it.
