### ISSUE TITLE
[LabelBot] Bot unassigning issue from a user when adding labels

### ISSUE THREAD

**Issue by kalyc** [MXNetEdge/mxnet-infrastructure#40]
See https://github.com/apache/incubator-mxnet/issues/7247
Could you please take a look at what is going on?

**Comment by marcoabreu** [comment]
Fyi, That action was executed by your account and not the one the label bot is using

**Comment by kalyc** [comment]
Re-tested it, added the label correctly. Not sure how did the issue get unassigned though. Closing issue for now.
