### ISSUE TITLE
Label name mismatch and Grammatical correctness of bot

### ISSUE THREAD

**Issue by ChaiBapchya** [MXNetEdge/mxnet-infrastructure#62]
2 nitpicks
With reference to comment from label bot on issue https://github.com/apache/incubator-mxnet/issues/14003
1. MXNet Label bot recommends label "Feature" but the right name of label is "Feature request"
2. If label bot recommends 1 label - it should be saying
"Here is my recommended label" 
Our bot should be grammatically correct too

**Comment by marcoabreu** [comment]
#1 is a valid case where the prediction is just wrong. We also have context specific labels (e.g. some for issues, some for PRs).

I don't think that #2 is really necessary tbh, it just overcomplicates code and introduced more branching. A simple "label(s)" should be sufficient as an alternative

**Comment by ChaiBapchya** [comment]
Ah right. label(s) sounds good.
